const constants = {
	"GAMES": [
		"Starcraft",
		"Counter Strike",
		"Worms",
		"Diablo II",
		"Chivalry",
		"Doom / Doom II",
		"Prop Hunt",
		"Terraria Competition",
		"Mortal Kombat X",
		"Special Smash Event",
		"Wheel of Torture",
		"Heroes of Might & Magic III",
		"Evan Drink Penalty",
		"Evan Removes His Pants",
		"Evan Drink Assignment",
		"Half Life 2",
		"Company of Heroes",
		"Day Z",
		"Duke3D",
		"Aliens vs. Predator",
		"Evan's Choice",
		"L4D2",
		"Alien Swarm",
		"Spin Again",
	],
	"MP3": [
		"o-fortuna.mp3"
	],
	"COLORS_DEFAULT": [
		"246B61",
		"6BA099",
		"43857C",
		"0D5047",
		"00352E",
		"2D4671",
		"051838",
		"152C55",
		"4D658D",
		"7689A9",
		"408E2F",
		"0C4700",
		"216A12",
		"68B159",
		"9AD58E"
	]
};